[package]
name = "libvisa"
description = "Bindings to the VISA library"
version = "0.1.0"
edition = "2021"

license = "MIT"
repository = "https://github.com/caliangroup/libvisa"
readme = "README.md"

[dependencies]